In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

In [12]:
# check the columns of electrical buildings csv for specific columns

elec_cols = pd.read_csv('data/electricity_cleaned.txt', nrows=0).columns
print(len(elec_cols))

# search for number of columns with Panther and (Education or Office)
# include the timestamp column for analysis
search_pattern = r'^timestamp$|Panther.*(?:education|office)'
matched_cols = elec_cols[elec_cols.str.contains(search_pattern, regex=True)]

print(len(matched_cols))
matched_cols

1579
55

Index(['timestamp', 'Panther_office_Hannah', 'Panther_education_Teofila',
       'Panther_education_Jerome', 'Panther_education_Misty',
       'Panther_office_Catherine', 'Panther_education_Tina',
       'Panther_education_Janis', 'Panther_office_Patti',
       'Panther_office_Lauretta', 'Panther_office_Valarie',
       'Panther_office_Karla', 'Panther_education_Quintin',
       'Panther_office_Graham', 'Panther_office_Larry',
       'Panther_education_Violet', 'Panther_office_Ruthie',
       'Panther_education_Edna', 'Panther_office_Garth',
       'Panther_education_Sophia', 'Panther_office_Shauna',
       'Panther_education_Hugh', 'Panther_office_Jesus',
       'Panther_office_Taryn', 'Panther_education_Annetta',
       'Panther_office_Otto', 'Panther_education_Ivan',
       'Panther_education_Alecia', 'Panther_office_Christian',
       'Panther_education_Rosalie', 'Panther_education_Jonathan',
       'Panther_office_Clementine', 'Panther_education_Neal',
       'Panther_office_Danica', 'Panther_education_Mohammad',
       'Panther_office_Christin', 'Panther_education_Enriqueta',
       'Panther_education_Shelton', 'Panther_education_Aurora',
       'Panther_office_Antonette', 'Panther_office_Kristen',
       'Panther_office_Brent', 'Panther_education_Vincent',
       'Panther_education_Mattie', 'Panther_education_Genevieve',
       'Panther_education_Diann', 'Panther_education_Emily',
       'Panther_education_Scarlett', 'Panther_education_Zelda',
       'Panther_office_Jeane', 'Panther_office_Lavinia', 'Panther_office_Lois',
       'Panther_education_Gina', 'Panther_education_Karri',
       'Panther_education_Cleopatra'],
      dtype='str')

In [13]:
# load electric consumption profiles of education and office buildings
df_elec = pd.read_csv('data/electricity_cleaned.txt',
                index_col=0,
                usecols=matched_cols)
print(df_elec.shape)
df_elec.head()

(17544, 54)

,Panther_office_Hannah,Panther_education_Teofila,Panther_education_Jerome,Panther_education_Misty,Panther_office_Catherine,Panther_education_Tina,Panther_education_Janis,Panther_office_Patti,Panther_office_Lauretta,Panther_office_Valarie,...,Panther_education_Diann,Panther_education_Emily,Panther_education_Scarlett,Panther_education_Zelda,Panther_office_Jeane,Panther_office_Lavinia,Panther_office_Lois,Panther_education_Gina,Panther_education_Karri,Panther_education_Cleopatra
timestamp,,,,,,,,,,,,,,,,,,,,,
2016-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# url_e = 'https://media.githubusercontent.com/media/buds-lab/building-data-genome-project-2/refs/heads/master/data/meters/cleaned/electricity_cleaned.csv'
# url_w = 'https://media.githubusercontent.com/media/buds-lab/building-data-genome-project-2/refs/heads/master/data/weather/weather.csv'
# df_weather = pd.read_csv(url_w)
# df_elec = pd.read_csv(url_e, usecols=['timestamp', 'Bear_education_Mary', 'Bear_office_Gene'])

In [14]:
# filter the columns of the weather csv

w_cols = pd.read_csv('data/weather.txt', nrows=0).columns
print(w_cols)

# site_id must correspond to Panther site
df_weather = pd.read_csv('data/weather.txt', index_col=0)
df_weather = df_weather[df_weather['site_id']=='Panther']
print(df_weather.shape)
df_weather.head()

Index(['timestamp', 'site_id', 'airTemperature', 'cloudCoverage',
       'dewTemperature', 'precipDepth1HR', 'precipDepth6HR', 'seaLvlPressure',
       'windDirection', 'windSpeed'],
      dtype='str')
(17544, 9)

,site_id,airTemperature,cloudCoverage,dewTemperature,precipDepth1HR,precipDepth6HR,seaLvlPressure,windDirection,windSpeed
timestamp,,,,,,,,,
2016-01-01 00:00:00,Panther,19.4,NaN,19.4,0.0,NaN,NaN,0.0,0.0
2016-01-01 01:00:00,Panther,21.1,6.0,21.1,-1.0,NaN,1019.4,0.0,0.0
2016-01-01 02:00:00,Panther,21.1,NaN,21.1,0.0,NaN,1018.8,210.0,1.5
2016-01-01 03:00:00,Panther,20.6,NaN,20.0,0.0,NaN,1018.1,0.0,0.0
2016-01-01 04:00:00,Panther,21.1,NaN,20.6,0.0,NaN,1019.0,290.0,1.5